project_id = "adljdeekwifwcdcgbpit"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.fetch-instagram]
verify_jwt = false

[functions.analyze-profile]
verify_jwt = false

[functions.generate-strategy]
verify_jwt = false

[functions.generate-creative]
verify_jwt = false

[functions.square-proxy]
verify_jwt = false

[functions.sync-instagram-profile]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.get-paid-users]
verify_jwt = true

[functions.user-data-storage]
verify_jwt = false

[functions.admin-data-storage]
verify_jwt = true

[functions.register-paid-user]
verify_jwt = false

[functions.login-paid-user]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.verify-admin]
verify_jwt = true